#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

EXPECTED_NAMES = {
    "HKVariants",
    "HKVariantsRev",
    "HKVariantsRevPhrases",
    "JPShinjitaiCharacters",
    "JPShinjitaiPhrases",
    "JPVariants",
    "JPVariantsRev",
    "STCharacters",
    "STPhrases",
    "TSCharacters",
    "TSPhrases",
    "TWPhrasesCustom",
    "TWPhrasesCustomRev",
    "TWPhrasesIT",
    "TWPhrasesName",
    "TWPhrasesOther",
    "TWPhrasesRev",
    "TWVariants",
    "TWVariantsRev",
    "TWVariantsRevPhrases",
}

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT.parent / "OpenCC" / "src" / "OpenCC" / "Internal" / "DictData.cs"
DEFAULT_OUTPUT = ROOT / "src" / "opencc_py" / "dict_data.py"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Python dictionary constants from C# DictData.cs.")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    constants = parse_constants(args.source.read_text(encoding="utf-8-sig"))
    missing = EXPECTED_NAMES - constants.keys()
    if missing:
        missing_names = ", ".join(sorted(missing))
        raise SystemExit(f"Missing expected DictData constants: {missing_names}")

    args.output.write_text(render(constants), encoding="utf-8")
    return 0


def parse_constants(source: str) -> dict[str, str]:
    pattern = re.compile(r'public const string (?P<name>\w+) = """(?P<value>.*?)""";', re.DOTALL)
    return {match.group("name"): match.group("value") for match in pattern.finditer(source)}


def render(constants: dict[str, str]) -> str:
    lines = [
        "# Generated by tools/generate_dict_data.py from OpenCC/src/OpenCC/Internal/DictData.cs.",
        "# Do not edit by hand.",
        "",
    ]

    for name in sorted(constants):
        py_name = to_upper_snake(name)
        value = constants[name]
        entries = [e for e in value.split("|") if e]
        multiline = "\n".join(entries) + "\n"
        lines.append(f'{py_name} = """\\\n{multiline}"""')
    lines.append("")
    lines.append("DICT_METADATA = {")
    for name in sorted(constants):
        py_name = to_upper_snake(name)
        value = constants[name]
        entries = [e for e in value.split("|") if e]
        multiline = "\n".join(entries) + "\n"
        entry_count = len(entries)
        digest = hashlib.sha256(multiline.encode("utf-8")).hexdigest()
        lines.append(f"    {py_name!r}: {{'entries': {entry_count}, 'sha256': {digest!r}}},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def to_upper_snake(name: str) -> str:
    words = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", name)
    return "_".join(word.upper() for word in words)


if __name__ == "__main__":
    raise SystemExit(main())
